#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Author: Mathew Cosgrove
# @Date:   2014-11-26 08:07:43
# @Last Modified by:   Mathew Cosgrove
# @Last Modified time: 2014-12-05 22:24:31

from QtBooty import graphs

class CpuStats():
  cpu_usage = graphs.TimeSeries(interval=1000, ylim=[0,100])
  app.add_widget(cpu_usage)

  psutil.cpu_percent(interval=None)
  start_time = time.time()

  for p in range(0, psutil.cpu_count()):
    cpu_usage.add_line(p, color='r')

  def psutil_data_update():
    usage = psutil.cpu_percent(interval=None, percpu=True)
    t = time.time() - start_time
    for p in range(0, psutil.cpu_count()):
      cpu_usage.add_data_point(p, t, usage[p])


# 'AccessDenied'
# 'BOOT_TIME'
# 'CONN_CLOSE'
# 'CONN_CLOSE_WAIT'
# 'CONN_CLOSING'
# 'CONN_ESTABLISHED'
# 'CONN_FIN_WAIT1'
# 'CONN_FIN_WAIT2'
# 'CONN_LAST_ACK'
# 'CONN_LISTEN'
# 'CONN_NONE'
# 'CONN_SYN_RECV'
# 'CONN_SYN_SENT'
# 'CONN_TIME_WAIT'
# 'Error'
# 'NUM_CPUS'
# 'NoSuchProcess'
# 'Popen'
# 'Process'
# 'STATUS_DEAD'
# 'STATUS_DISK_SLEEP'
# 'STATUS_IDLE'
# 'STATUS_LOCKED'
# 'STATUS_RUNNING'
# 'STATUS_SLEEPING'
# 'STATUS_STOPPED'
# 'STATUS_TRACING_STOP'
# 'STATUS_WAITING'
# 'STATUS_WAKING'
# 'STATUS_ZOMBIE'
# 'TOTAL_PHYMEM'
# 'TimeoutExpired'
# '_POSIX'
# '_PY3'
# '_TOTAL_PHYMEM'
# '_WINDOWS'
# '__all__'
# '__author__'
# '__builtins__'
# '__class__'
# '__delattr__'
# '__dict__'
# '__doc__'
# '__file__'
# '__format__'
# '__getattribute__'
# '__hash__'
# '__init__'
# '__module__'
# '__name__'
# '__new__'
# '__package__'
# '__path__'
# '__reduce__'
# '__reduce_ex__'
# '__repr__'
# '__setattr__'
# '__sizeof__'
# '__str__'
# '__subclasshook__'
# '__version__'
# '__weakref__'
# '_assert_pid_not_reused'
# '_common'
# '_compat'
# '_deprecated'
# '_deprecated_method'
# '_last_cpu_times'
# '_last_cpu_times_2'
# '_last_per_cpu_times'
# '_last_per_cpu_times_2'
# '_module'
# '_nt_sys_diskio'
# '_nt_sys_netio'
# '_pmap'
# '_psosx'
# '_psplatform'
# '_psposix'
# '_timer'
# '_wraps'
# 'avail_phymem'
# 'avail_virtmem'
# 'boot_time'
# 'callable'
# 'cpu_count'
# 'cpu_percent'
# 'cpu_times'
# 'cpu_times_percent'
# 'defaultdict'
# 'disk_io_counters'
# 'disk_partitions'
# 'disk_usage'
# 'errno'
# 'get_pid_list'
# 'get_process_list'
# 'get_users'
# 'long'
# 'net_connections'
# 'net_io_counters'
# 'network_io_counters'
# 'os'
# 'phymem_usage'
# 'pid_exists'
# 'pids'
# 'process_iter'
# 'pwd'
# 'signal'
# 'subprocess'
# 'swap_memory'
# 'sys'
# 'test'
# 'time'
# 'total_virtmem'
# 'used_phymem'
# 'used_virtmem'
# 'users'
# 'version_info'
# 'virtmem_usage'
# 'virtual_memory'
# 'wait_procs'
# 'warnings'
